<?php

namespace Tests\Feature\Admin\Admin;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class MemberTest extends TestCase
{
    use RefreshDatabase;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
        $this->user = User::factory()->create();
    }

    protected function tearDown(): void
    {
        Schema::disableForeignKeyConstraints();
        User::truncate();
        Schema::enableForeignKeyConstraints();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_member_create()
    {
        $response = $this->actingAs($this->user)->post(route('admin.member.store'), [
            'username'         => 'member_user',
            'password'         => 'password1234',
            'password_confirm' => 'password1234',
            'name'             => 'Member Name',
            'email'            => 'member@member.com',
            'cellphone'        => '010-2222-3333',
            'birthday'         => '900101',
        ]);

        $user = User::where('username', 'member_user')
                    ->where('type', 'member')
                    ->first();

        $response->assertRedirect(route('admin.member.show', $user->code));
    }

    public function test_member_show()
    {
        $this->actingAs($this->user)->post(route('admin.member.store'), [
            'username'         => 'member_user',
            'password'         => 'password1234',
            'password_confirm' => 'password1234',
            'name'             => 'Member Name',
            'email'            => 'member@member.com',
            'cellphone'        => '010-2222-3333',
            'birthday'         => '900101',
        ]);

        $user = User::where('username', 'member_user')
                    ->where('type', 'member')
                    ->first();

        $response = $this->actingAs($this->user)->get(route('admin.member.show', $user->code));

        $response->assertStatus(200);
        $response->assertSeeText('member_user');
        $response->assertSeeText($user->code);
    }

    public function test_member_update()
    {
        $this->actingAs($this->user)->post(route('admin.member.store'), [
            'username'         => 'member_user',
            'password'         => 'password1234',
            'password_confirm' => 'password1234',
            'name'             => 'Member Name',
            'email'            => 'member@member.com',
            'cellphone'        => '010-2222-3333',
            'birthday'         => '900101',
        ]);

        $user = User::where('username', 'member_user')
                    ->where('type', 'member')
                    ->first();

        $response = $this->actingAs($this->user)->put(route('admin.member.update', $user->code), [
            'name' => 'Member Update Name',
        ]);

        $updatedUser = User::where('username', 'member_user')
                           ->where('type', 'member')
                           ->first();

        $response->assertRedirect(route('admin.member.show', $user->code));
        $this->assertEquals('Member Update Name', $updatedUser->name, 'Name is not equal.');
    }

    public function test_member_list()
    {
        $response = $this->actingAs($this->user)->get(route('admin.member.index'));

        $response->assertStatus(200);
    }
}
